# Generated by Django 2.1.1 on 2019-12-09 13:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
